update config

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,50 +1,54 @@
 name: Playwright Tests
 on:
   push:
-    branches: [ main, master ]
+    branches: [main, master]
   pull_request:
-    branches: [ main, master ]
+    branches: [main, master]
+
+env:
+  FORCE_COLOR: 1
+
 jobs:
   test:
     timeout-minutes: 60
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-node@v3
-      with:
-        node-version: 14
-    - name: Install dependencies
-      run: npm ci
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 14
+      - name: Install dependencies
+        run: npm ci
 
-    # - name: Start WordPress Env
-    #   run: |
-    #     npm run start:env 
+      # - name: Start WordPress Env
+      #   run: |
+      #     npm run start:env
 
-    # - name: Install Playwright Browsers
-    #   run: npx playwright install chromium
+      # - name: Install Playwright Browsers
+      #   run: npx playwright install chromium
 
-    - name: Run Playwright tests
-      id: test
-      run: npx playwright test || true
+      - name: Run Playwright tests
+        id: test
+        run: npx playwright test || true
 
-    # - name: Publish Test Report
-    #   uses: mikepenz/action-junit-report@v3
-    #   if: always() 
-    #   with:
-    #     report_paths: "junit-report/e2e-results.xml"
-    #     job_summary: false
-    #     annotate_only: true,
-    #     # include_passed: true,
-    #     # check_retries: true,
-    #     # detailed_summary: true,
-    #     check_name: 'E2E Test Report'
-    #     summary: 'E2E Test Summary Report (JUnit)_summary'
-        # annotate_notice: true,
-        # job_name: 'e2e2e2e2e2e2e2e_jobName'
+      # - name: Publish Test Report
+      #   uses: mikepenz/action-junit-report@v3
+      #   if: always()
+      #   with:
+      #     report_paths: "junit-report/e2e-results.xml"
+      #     job_summary: false
+      #     annotate_only: true,
+      #     # include_passed: true,
+      #     # check_retries: true,
+      #     # detailed_summary: true,
+      #     check_name: 'E2E Test Report'
+      #     summary: 'E2E Test Summary Report (JUnit)_summary'
+      # annotate_notice: true,
+      # job_name: 'e2e2e2e2e2e2e2e_jobName'
 
-    - uses: actions/upload-artifact@v3
-      if: steps.test.outcome == 'success' 
-      with:
-        name: playwright-report
-        path: test-results
-        retention-days: 30
+      - uses: actions/upload-artifact@v3
+        if: steps.test.outcome == 'success'
+        with:
+          name: playwright-report
+          path: test-results
+          retention-days: 30
